image:
  file: .gitpod.Dockerfile

tasks:
  - name: Start Couchbase
    command:  ./startcb.sh && gp sync-done startcb
  - name: Log use
    command: curl -s 'https://da-demo-images.s3.amazonaws.com/runItNow_outline.png?couchbase-example=scala-quickstart-repo&source=gitpod' > /dev/null
  - name: Start app
    init: sbt compile
    command: gp sync-await startcb && sbt run
  - name: Load Swagger page for Akka HTTP
    command: sleep 10 && gp preview $(gp url 8081)/docs

ports:
  # Akka HTTP
  - port: 8081
    onOpen: ignore
  # http4s
  - port: 8082
    onOpen: ignore
  # Play
  - port: 8083
    onOpen: ignore
  # Couchbase administrator
  - port: 8091
    onOpen: open-browser
  - port: 8092-10000
    onOpen: ignore
  - port: 4369
    onOpen: ignore

vscode:
  extensions:
    - scala-lang.scala
#    - scalameta.metals
